### ISSUE TITLE
過期害人進去

### ISSUE THREAD

**Issue by jidanni** [PDIS/1922.gov.tw#22]
![Screenshot_20211101-085830.jpg](https://user-images.githubusercontent.com/1230959/139608010-73a1384b-9eae-49d3-b57a-bdcc11488d63.jpg)
明明過期...

辛辛苦苦填表進去...

**Comment by jidanni** [comment]
...才說過期。

那麼不要讓民眾填表。

**Comment by jidanni** [comment]
正如本 Github, 沒興趣看就不要讓民眾回報 issues.

**Comment by audreyt** [comment]
？我都有看。如果不讓民眾查詢，如何知道是當期或過期？

**Comment by jidanni** [comment]
如果民眾忽略「服務時間 10/27 19:00 ~ 10/28 12:00」，貿然繼續...

下場即「提示

×

現在非服務期間
[服務期間 2021/10/27 19:00:00 到 2021/10/28 12:00:00 ]
[現在時間:2021年11月01日 12:42:17][PG35][qap37]」。

**Comment by jidanni** [comment]
當然如一樓寫圖書館開放時間，人家沒看，白爬到三樓吃閉門羹...不如一樓拉鐵鍊。

**Comment by jidanni** [comment]
其實民眾絕非忽略，而是認為既然表單仍能填，代表前言是錯的。

**Comment by jidanni** [comment]
當然官方也無罪：不看閃光燈墜崖自負，但仍宜立欄杆。

**Comment by jidanni** [comment]
免處置，但麻煩留
![20211101T225212](https://user-images.githubusercontent.com/1230959/139691466-0133429f-c295-4fff-8888-7964cc6f7dfc.jpg)
眼睛，代表「已讀」，否則「管理人一定沒看到」。
