### ISSUE TITLE
使用者無法查已打了幾劑

### ISSUE THREAD

**Issue by jidanni** [PDIS/1922.gov.tw#23]
無法確認系統與黃卡一致否。

**Comment by audreyt** [comment]
https://vas.1922.gov.tw/vas/?language=en "Query" should show it.

**Comment by jidanni** [comment]
絕對沒有！
或許已有打第一劑者會有寫
「您已打 第一劑 某某 疫苗」...

**Comment by jidanni** [comment]
惟尚未打者..其隻字未提！

**Comment by jidanni** [comment]
故務必說「您尚未打 任何 疫苗」。

**Comment by jidanni** [comment]
否則民眾難查衛生所已將施打事實報中央否。

**Comment by audreyt** [comment]
一劑、二劑都有字樣說明，所以如果沒有，那就是還沒有報中央。

所以您是希望加上文字，說明系統尚未接到 COVID-19 疫苗接種紀錄？

**Comment by jidanni** [comment]
對！
因為只有內幕的人才知道沒有寫等於沒有打。

**Comment by jidanni** [comment]
建議可直接作黃卡格架。
大家看到「第一劑 無資料」， 「第二劑 無資料」，就知道了。

說不定已經像黃卡，我不知道。

**Comment by audreyt** [comment]
感謝建議。目前請先使用「健保快易通」的查詢界面，我們會在接下來的「健康資訊數位證明簽發平台」處理這件事。

**Comment by jidanni** [comment]
我記得「健保快易通」APP 不開放給外國人。

對齁，我忘記說要寫哪天打的。否則無法查衛生所是否亂填。

**Comment by jidanni** [comment]
2018/12/5: 0800 專線人員確定咱外籍人士只能用電腦版，故此 app 可休想。很不公平。

**Comment by jidanni** [comment]
見近期 Google Play 英文評論，仍排外至今。且於 Google Play 無任何警語，故可憐外國人各花數小時始知無法用。

**Comment by audreyt** [comment]
For  ARC/APRC holders, if you have a monthly subscription plan to a mobile phone number, the NHI Express App should work.

**Comment by jidanni** [comment]
據下載者，該 APP [根本未支援兩英文字開頭之證號！](https://play.google.com/store/apps/details?id=com.nhiApp.v1&reviewId=gp%3AAOqpTOHnfPGH-eyZQbBcBALVG7nUyqJC7oveHPoipAd0Y4I5tWBdaMngtPMNRpfRhwpNCOKbjghnA7YsvGdGpYk)

不管。仍能用
https://myhealthbank.nhi.gov.tw/ihke0002/ihke2021s01.aspx
我的首頁> 健康資料 > 檢驗檢查結果 > COVID-19 疫苗接種/病毒檢測結果
```
身分證號：LP000...
疫苗接種
～無資料～
【說明】
「疫苗接種資料」係向疾管署系統介接取得，首次取得資料需要處理時間較長；若您已有施打疫苗，請稍後再查看資料，造成不便，敬請見諒！
註：參見備註5、6。
```
（應加「超過一週就不正常！兩週不妙…」）

**Comment by jidanni** [comment]
（[新單英文字開頭者亦同失敗](https://play.google.com/store/apps/details?id=com.nhiApp.v1&reviewId=gp%3AAOqpTOEttFwcWsrHehFZzGALPTkmnQq2tduOzhJq4tDWGRORCjYXeODDkKCyqjUTK9U-ytM446HT2wUD2rxKLlU)。 或許幕後原因非此，但結論： 請外國人用該 APP: 休想。）
（好了。評論單 100 個中的確有一位成功。）

**Comment by jidanni** [comment]
（中市衛生局說，
資料更正後，
需幾天才看得到：
- 1922 平台： 幾天
- 健康存摺網站： 一個月也算正常
- 快易通 APP： 我忘記問

）

**Comment by jidanni** [comment]
已看到：
```
備註
您已接種過BN疫苗，最早可接種第2劑日期：110年11月10日
如有接種資料疑義，請向原接種單位或所轄衛生所(局)洽詢。
```
惟，
- BNT 非 BN
- 應說 「您已於110年10月13日接種過BNT疫苗…」

**Comment by jidanni** [comment]
```
【提醒】已接種2劑COVID-19疫苗
如有接種資料疑義，請向原接種單位或所轄衛生所(局)洽詢。
```
好。可能未提及哪劑哪牌哪日打的是為了保密。
那麼只剩下應註明 `您尚未接種疫苗…`
